contact_links:
  - name: ğŸ’¬ OpenSearch Community Slack Workspace
    url: https://opensearch.org/slack.html
    about: Chat with community members and maintainers here.
  - name: ğŸ¤· OpenSearch Community Forum
    url: https://forum.opensearch.org/
    about: Ask and answer OpenSearch usage questions here.
  - name: ğŸ” Report a Security Issue
    url: https://github.com/opensearch-project/.github/blob/main/SECURITY.md
    about: Please e-mail security@opensearch.org. Do not create a public GitHub issue.
